url: jdbc:postgresql://localhost:5432/monitorService
username: user
password: secret

spring:
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true
    url: jdbc:postgresql://localhost:5432/monitorService
    user: user
    password: secret
  datasource:
    url: jdbc:postgresql://localhost:5432/monitorService
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver